config/routes.rb
Rails.application.routes.draw do
    resources :images




    resources :idols do
      collection do
        get :backup_to_dump
        get :restore_from_dump
      end
    end



  
    	

  	resources :articles
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  	
  	



  	devise_for :admins, path: 'admins', controllers: 
  	{
  		registrations: 	'admins/registrations',
  		sessions: 		'admins/sessions',
  		confirmations: 	'admins/confirmations',
  		passwords: 		'admins/passwords',
  		unlocks: 		'admins/unlocks'

  		# Not including omniauth because it's not enabled in the Admin Model
  		# ,omniauth_callbacks: 'admins/omniauth_callbacks'
  	}






    devise_for :users, path: 'users', controllers:
    {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      confirmations: 'users/confirmations',
      passwords: 'users/passwords',
      unlocks: 'users/unlocks'
    }





      root 'articles#index'
end

app/models/idol.rb
class Idol < ApplicationRecord
		has_many :talents, dependent: :destroy

		validates :last_name, presence: true



		
end

app/controllers/idols_controller.rb
class IdolsController < ApplicationController
  before_action :set_idol, only: [:show, :edit, :update, :destroy]

  # GET /idols
  # GET /idols.json
  def index
    @idols = Idol.all




    respond_to do | format |
        format.html

        format.pdf do

            prawn_pdf = IdolPdf.new(@idols, view_context)

            send_data prawn_pdf.render, filename: "shyshyshy.pdf", type: 'application/pdf', disposition: "inline"
        end

    end
  end


  # GET /idols/1
  # GET /idols/1.json
  def show


  end







  # GET /idols/new
  def new
    @idol = Idol.new
    @talents = @idol.talents.build
  end

  # POST /idols
  # POST /idols.json
  def create
    @idol = Idol.new(idol_params)
    @talents = @idol.talents.build(talent_params)
    respond_to do |format|
      if @idol.save && @talents.save
          format.html { redirect_to idols_path, notice: 'Idol was successfully debuted.' }
          format.json { render :show, status: :created, location: @idol }
      else
          format.html { redirect_to new_idol_path, notice: 'Failed to register Idol' }
          format.json { render json: @idol.errors, status: :unprocessable_entity }
      end
    end
  end





  # GET /idols/1/edit
  def edit
    @talents = @idol.talents.last
  end

  # PATCH/PUT /idols/1
  # PATCH/PUT /idols/1.json
  def update
      @talents = @idol.talents.last
      respond_to do |format|
          if @idol.update(idol_params) && @talents.update(talent_params)
              shiori = KuboshiMailer.new_shiorichan(@idol, Admin.find(3))
              shiori.deliver_now

              format.html { redirect_to idols_path, notice: 'Idol was successfully updated.' }
              format.json { render :show, status: :created, location: @idol }

          else
              
              format.html { render :edit, notice: 'Failed to update Idol' }
              format.json { render json: @idol.errors, status: :unprocessable_entity }
          end

      end
  end






  # DELETE /idols/1
  # DELETE /idols/1.json
  def destroy
    @idol.destroy
    respond_to do |format|
      format.html { redirect_to idols_url, notice: 'Idol was successfully destroyed.' }
      format.json { head :no_content }
    end
  end




  def backup_to_dump
    @idol = Idol.last
    
    user = "postgres"
    host_development = "127.0.0.1"

    cmd = "pg_dump --format=c --verbose --username=#{user} --host=#{host_development} --no-owner --no-acl --no-password --file=c:/backup.dump twiceland"

    system cmd

    render :show, notice: "Shyshyshy #{cmd}"
  end


  def restore_from_dump

    @idol = Idol.first

    user = "postgres"
    host_development = "127.0.0.1"


    cmd = "pg_restore --format=c --verbose --username=#{user} --host=#{host_development} --clean --no-owner --no-acl --dbname=twiceland c:/backup.dump"

    system cmd

    render :show, notice: "Jeoreujima #{cmd}"
  end






  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idol
      @idol = Idol.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idol_params
      params.require(:idol).permit(:last_name, :first_name)
    end

    def talent_params
      params.require(:idol).require(:talents).permit(:description)
    end

end

app/helpers/idols_helper.rb
module IdolsHelper
end

app/views/idols/_form.html.erb
<%= form_with(model: idol, local: true) do |form| %>
  
  <!-- Errors -->
  <% if idol.errors.any? %>
      <div id="error_explanation">
          <h2><%= pluralize(idol.errors.count, "error") %> prohibited this idol from being saved:</h2>

          <ul>
          <% idol.errors.full_messages.each do |message| %>
              <li><%= message %></li>
          <% end %>
          </ul>
      </div>
  <% end %>


  <% if @talents.errors.any? %>
      <div id="error_explanation">
          <h2><%= pluralize(@talents.errors.count, "error") %> prohibited this idol from being saved:</h2>

          <ul>
          <% @talents.errors.full_messages.each do |message| %>
              <li><%= message %></li>
          <% end %>
          </ul>
      </div>
  <% end %>

  <!-- Errors End -->



  <div class="field">
      <%= form.label :last_name %>
      <%= form.text_field :last_name, id: :idol_last_name %>
  </div>

  <div class="field">
      <%= form.label :first_name %>
      <%= form.text_field :first_name, id: :idol_first_name %>
  </div>




  <!-- Fields for Talents -->
  <div class="field">
      <%= form.fields_for :talents, @talents do |talent_field| %>
          <%= talent_field.label :description %>
          <%= talent_field.text_field :description, id: :idol_first_name %>
      <% end %>
  </div>
  <!-- Fields for Talents End -->





  <div class="actions">
      <%= form.submit %>
  </div>
<% end %>

app/views/idols/edit.html.erb
<h1>Editing Idol</h1>

<%= render 'form', idol: @idol %>

<%= link_to 'Show', @idol %> |
<%= link_to 'Back', idols_path %>

app/views/idols/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Idols</h1>

<table>
  <thead>
    <tr>
      <th>Last name</th>
      <th>First name</th>
      <th>Talent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @idols.each do |idol| %>
      <tr>
        <td><%= idol.last_name %></td>
        <td><%= idol.first_name %></td>
        <td><%= idol.talents.last.description if idol.talents.any? %></td>
        <td><%= link_to 'Show', idol %></td>
        <td><%= link_to 'Edit', edit_idol_path(idol) %></td>
        <td><%= link_to 'Destroy', idol, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<br>
<br>

<%= link_to 'Run a backup', backup_to_dump_idols_path %>
<%= link_to 'Restore', restore_from_dump_idols_path %>
<%= link_to 'New Idol', new_idol_path %>
<%= link_to 'Shyshyshy.pdf', idols_path(format: 'pdf') %>

app/views/idols/new.html.erb
<h1>New Idol</h1>

<%= render 'form', idol: @idol %>

<%= link_to 'Back', idols_path %>

app/views/idols/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Last name:</strong>
  <%= @idol.last_name %>
</p>

<p>
  <strong>First name:</strong>
  <%= @idol.first_name %>
</p>

<%= link_to 'Edit', edit_idol_path(@idol) %> |
<%= link_to 'Back', idols_path %>